
[id="con-subassembly-concept-module_{context}"]

= Subassembly concept module


Include a short introduction that explains what this module is about.


ifeval::["{context}" == "sample-assembly-1"]
This paragraph is about sample-assembly-1 and should be visible only in that story. The `context:` definition in the assembly (`sample-assembly-1`) matches the context in the ifeval statement.
endif::[]

ifeval::["{context}" == "sample-assembly-2"]
.Conditional context
This paragraph is about sample-assembly-2 and should be visible only in that story. The `context:` definition in the assembly (`sample-assembly-2`) matches the context in the ifeval statement.
endif::[]

The contents of a concept module give the user descriptions and explanations needed to understand and use a product.

* Look at nouns and noun phrases in related procedure modules and assemblies to find the concepts to explain to users.
* Explain only things that are visible to users. Even if a concept is interesting, it probably does not require explanation if it is not visible to users.
* Do not include any instructions to perform an action, such as executing a command. Action items belong in procedure modules.

.Additional resources (this is part of the concept module)

* A bulleted list of links to other material closely related to the contents of the concept module.
* This link uses the Asciidoc xref syntax: xref:proc-procedure-module_{context}.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
